#!/usr/bin/env python3
"""
Mock LLM Service - Returns mock responses for testing
This service mocks the LLM service responses until actual GPU deployment.
"""
from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn
import os
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
)
logger = logging.getLogger("mock_llm_service")

app = FastAPI(
    title="Mock LLM Service",
    description="Mock LLM service for testing - returns mock responses",
    version="1.0.0"
)

class GenerateRequest(BaseModel):
    context: str
    query: str
    model: str = "qwen"

class GenerateResponse(BaseModel):
    answer: str
    model: str

@app.get("/health")
def health():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "service": "mock-llm-service",
        "gpu_available": False,
        "gpu_memory": {},
        "models_loaded": ["qwen", "mistral", "llama"],
        "note": "This is a mock service. Replace with actual LLM service for GPU deployment."
    }

@app.post("/generate", response_model=GenerateResponse)
def generate(request: GenerateRequest):
    """
    Mock LLM generation endpoint
    Returns a mock response based on the query
    """
    logger.info(f"Mock LLM generate called - Model: {request.model}, Query: {request.query[:100]}...")
    
    # Simple mock response that simulates LLM behavior
    context_length = len(request.context)
    query_length = len(request.query)
    
    # Generate a mock answer based on query
    mock_answer = f"""Based on the provided context, here is a mock response to your query: "{request.query}"

**Mock LLM Response:**
This is a mock LLM response generated for testing purposes. When you deploy to GPU, this will be replaced with actual LLM inference from the {request.model} model.

**Context Information:**
- Context length: {context_length:,} characters
- Query length: {query_length} characters
- Model requested: {request.model}

**Note:** This response is generated by the mock LLM service. To get actual LLM responses, deploy the real LLM service to GPU nodes.

**Sample Answer Format:**
The mock service simulates the structure of a real LLM response. In production, the actual LLM service will:
1. Process the context and query
2. Generate a coherent answer using the {request.model} model
3. Return the answer in this same format.
"""
    
    logger.info(f"Mock response generated - Answer length: {len(mock_answer)} characters")
    
    return GenerateResponse(
        answer=mock_answer,
        model=request.model
    )

@app.get("/")
def root():
    """Root endpoint"""
    return {
        "service": "mock-llm-service",
        "version": "1.0.0",
        "status": "running",
        "endpoints": {
            "health": "/health",
            "generate": "/generate (POST)"
        }
    }

if __name__ == "__main__":
    port = int(os.getenv("LLM_SERVICE_PORT", "8001"))
    host = os.getenv("LLM_SERVICE_HOST", "0.0.0.0")
    
    logger.info(f"Starting Mock LLM Service on {host}:{port}")
    logger.info("This is a mock service for testing. Replace with actual LLM service for GPU deployment.")
    
    uvicorn.run(app, host=host, port=port)

